functions:
  test-a:
    path: test_a
    file-name: a.py
  test-group-a:
    path: group_a
    groups:
      - test-group
  test-group-b:
    path: group_b
    groups:
      - test-group
  test-b:
    path: test_b
    depends-on:
      - test-a
