name: Sieve Deploy
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run:
          echo "env_name=${GITHUB_REF//\//-}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install sievedata
      - run: python utils/ci.py
        env:
          SIEVE_API_KEY: ${{ secrets.SIEVE_API_KEY }}
          ORGANIZATION_NAME: sieve-internal
          SIEVE_TEST_ENV: ${{ steps.vars.outputs.env_name }}
